name: Deploy Laravel to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, bcmath, json, openssl

      - name: Install dependencies
        run: composer install --no-dev --optimize-autoloader

      - name: Deploy el EC2 via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            git config --global safe.directory "/var/www/Laravel"
            cd "/var/www/Laravel"
            sudo mkdir -p storage/logs
            sudo mkdir -p bootstrap/cache
            sudo chown -R ubuntu:ubuntu /var/www/Laravel
            sudo chmod -R 777 storage bootstrap/cache
            git pull origin main
            composer install --no-dev --optimize-autoloader
            php artisan migrate --force
            php artisan cache:clear
            php artisan config:cache
            php artisan route:cache
            sudo systemctl restart apache2